server:
  port: 8082

spring:
  application:
    name: ads-service
  datasource:
    url: jdbc:postgresql://localhost:5432/codebyz_ads
    username: postgres
    password: 122333
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

auth:
  base-url: http://localhost:8081

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

storage:
  uploads-dir: uploads
  ad:
    dir: ads
    public-url: /odnlicasjocdiahduhjcoinaurofrejdhiudosjkhfddddddddddddddddddddiopasdijkhieodfjhsiui0eodjifhureodihuosfdjfiles

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs

app:
  timezone: Europe/Istanbul
