services:
  postgres:
    image: postgres:16-alpine
    container_name: codebyz-postgres
    environment:
      POSTGRES_DB: codebyzplatform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 122333
    ports:
      - "5432:5432"
    volumes:
      - codebyz_pg_data:/var/lib/postgresql/data
volumes:
  codebyz_pg_data:
